server:
  port: 8565
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/commentdb?createDatabaseIfNotExist=true
    username: root
    password: root
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/commentdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: 'create-drop'